### ISSUE TITLE
What is singularity_pull_docker_container?

### ISSUE THREAD

**Issue by jpfeuffer** [nf-core/quantms#106]
And can we remove it?
It certainly should not be part of the modules since it does not seem to be nf-core specific.
If you want to keep it, it should go into a config file.

**Comment by ypriverol** [comment]
What do you mean @jpfeuffer.?

**Comment by jpfeuffer** [comment]
Did we introduce this variable?

**Comment by jpfeuffer** [comment]
Apparently it was a nf-core variable that was removed.
