### ISSUE TITLE
Some problem in learning quantms source code and OpenMS

### ISSUE THREAD

**Issue by liuxiawei** [nf-core/quantms#133]
Thank you to all the developers for their hard work! Recently, I have been learning the basics of OpenMS, and I have been using the data PXD015828 from PRIDE as a practice dataset. During this process, I have encountered the following issues. I referenced quantms（[https://github.com/nf-core/quantms/tree/master）](https://github.com/nf-core/quantms/tree/master%EF%BC%89) to build a set of scripts, and I encountered three issues during testing.
（OpenMS 3.1 installed from bioconda）
![image](https://github.com/nf-core/quantms/assets/5093541/5fa5c78d-4d2c-473b-86cd-807cd774f838)
### the difference of quantms pipeline figure and the code
The position of the consensusID step is inconsistent between the figure (https://github.com/nf-core/quantms/blob/master/docs/images/quantms_metro.png) and the source code. In the code, it is placed after rescoring, while in the figure, it is placed before rescoring. Does this inconsistency affect the experimental results? Which approach is better? Is it preferable to have consistency? 

### where  should be the best position of PeptideIndexer?
I faced Error in ProteomicsLFQ ( submitted to [OpenMS](https://github.com/OpenMS/OpenMS/issues/7260)), And I found the progress is omit in quantms, I want to put it back. I tried to add PeptideIndexer before ConsensusID, it it right?
### IDScoreSwitcher error (also submitted to [OpenMS](https://github.com/OpenMS/OpenMS/issues/7260))
I faced error when I use IDScoreSwitcher, I just skipped it Is it allowed to skip the IDScoreSwitcher?
Errorlog:
```
IDScoreSwitcher -in work/20170510_Joshi_9119/consensusID.idXML -out work/20170510_Joshi_9119/idscoreswitcher.idXML -new_score_orientation higher_better -threads 48 -debug 0 
Error: Unexpected internal error (Meta value '' not found for peptide hit with sequence 'SETNDS(Phospho)S(Phospho)S(Phospho)GS(Phospho)QS(Phospho)HQDASAASSAPPR', charge 2, score 1.0)
```

And I also faced some openms error report, I submit in [OpenMS](https://github.com/OpenMS/OpenMS/issues/7260), Thank you for your assistance. I hope to contribute to this program.

**Comment by jpfeuffer** [comment]
Yes the metro chart is wrong and should be corrected. No effects on results. ConsensusID wouldn't even work without rescoring to a comparable score. The rest of the questions were answered in the openms issue.

**Comment by liuxiawei** [comment]
Thanks！I have obtained preliminary results! Thank you for your support and assistance!
