### ISSUE TITLE
DIA test data SDRF file is missing required column

### ISSUE THREAD

**Issue by harper357** [nf-core/quantms#134]
### Description of the bug

I was trying to run the test data set using `test_full_data.config` and got an error saying there was a missing required column in SDRF file. It needs a `characteristics[biological replicate]` column. 

I posted in the nf-core/test-data slack channel and they suggested I make the bug report here first. 

### Command used and terminal output

```console
Error message:

 The following columns are mandatory and not present in the SDRF: characteristics[biological replicate] -- ERROR
  The column characteristics[biological replicate] is not present in the SDRF -- ERROR
  There were validation errors!
```
```


### Relevant files

_No response_

### System information

_No response_

**Comment by harper357** [comment]
Related to #39

**Comment by daichengxin** [comment]
fixed: https://github.com/nf-core/test-datasets/pull/1062
