### ISSUE TITLE
error in reference_channel

### ISSUE THREAD

**Issue by YoujiaMa** [nf-core/quantms#136]
### Description of feature

i have some error in when set reference_channel for my tmt run. i use tmt131N as my reference and run --reference_channel 131N.  it report that:

ERROR: Validation of pipeline parameters failed!
* --reference_channel: expected type: Number, found: String (131N)

**Comment by daichengxin** [comment]
Thanks for using. Fixed bug: https://github.com/bigbio/quantms/pull/331
