### ISSUE TITLE
AWS tests completely failing

### ISSUE THREAD

**Issue by jpfeuffer** [nf-core/quantms#23]
It runs LFQ:ID:DECOYDATABASE AND TMT:ID:DECOYDATABASE.

Why? @daichengxin

**Comment by daichengxin** [comment]
Sorry, I don't know, I haven't modified this after you modified the analysis pipeline based on the quantification type. It looks like both TMT and LFQ work.  
https://github.com/nf-core/quantms/blob/8ff9160827c46bd008ea9f191eb73c13a7057bf7/workflows/quantms.nf#L104-L124
