### ISSUE TITLE
test configs

### ISSUE THREAD

**Issue by CaroAMN** [nf-core/quantms#46]
### Missing test config
Hello, I wanted to mention that this pipeline is missing the standard test configuration. It would be great to include a test profile since it is an important part of all nf-core pipelines and it would help users to test the pipeline before actually using it with their own data.

### Errors
I then wanted  to test the pipeline with two of the existing test profiles and there I encountered some errors.

1. test_dia
the command that I used:
`nextflow run nf-core/quantms  -profile test_dia,cfc  --outdir results_dia`

The test produced an output but I think in the msstates_comparisons.tsv the column names do not match with the actual column values. The column names might be in the wrong order. I attached the output tsv.

2. test_lfq
the command that I used:
`nextflow run nf-core/quantms -r 1.0  -profile test_lfq,cfc  --outdir results_lfq`

The test_lfq didn't run through and gave the following error report:
<img width="960" alt="nextflow_tower_error" src="https://user-images.githubusercontent.com/64986570/178265006-61984d63-157a-4863-84f7-c0b1e49a7222.png">

Thanks in advance :) !

### Relevant files

[msstats_comparisons.csv](https://github.com/nf-core/quantms/files/9083633/msstats_comparisons.csv)

**Comment by jpfeuffer** [comment]
This should be done! Thanks for reporting!
We would appreciate feedback if it works now for you.
