### ISSUE TITLE
Move most modules from local into nf-core

### ISSUE THREAD

**Issue by jpfeuffer** [nf-core/quantms#63]
### Description of feature

Especially the ones from the openms/subfolder. So they can be reused for other pipelines.
They should be mostly nf-core compatible already but might require some tests and minor adaptions.

**Comment by rolivella** [comment]
FYI I'm working on moving the IDFilter: https://github.com/nf-core/modules/issues/2205

**Comment by jpfeuffer** [comment]
That's great. Having the first example will help other contributors to help out.

**Comment by rolivella** [comment]
Yes! But I think is not intrinsically related to `quantms` pipeline. nf-core modules are not linked to this pipeline, are general modules that can be reused into any pipeline...

And It's going to take me some time, is quite complex! I'll not finish it today in the hackathon.

**Comment by jpfeuffer** [comment]
Yes true, the first step is to make nf-core modules (e.g., out of the ones in quantms), which is a "global" nf-core task. Then we can start replacing the local ones here with the global ones.

**Comment by jonasscheid** [comment]
FYI: https://nf-co.re/modules/openms_idfilter

**Comment by jonasscheid** [comment]
And I had the time to do some more (simple) modules during the last hackathon 🥳 
https://github.com/nf-core/modules/tree/master/modules/nf-core/openms

**Comment by ypriverol** [comment]
This is a major refactoring. I will close the issue for now.
