### ISSUE TITLE
The run-command needs to be updated in documentation

### ISSUE THREAD

**Issue by charmoniumQ** [nf-core/quantms#68]
### Description of the bug

The commands in the documentation on nf-co.re and in this repository are wrong.

On the banner on the right-hand side of <https://nf-co.re/quantms>, it says this pipeline can be run with:

```bash
$ nextflow run nf-core/quantms -r 1.0 -profile test --outdir ../outdir
N E X T F L O W  ~  version 22.10.4
Unknown configuration profile: 'test'

Did you mean one of these?
    oist
```

In the `README.md` in this repository, it says it can be run with:

```bash
$ nextflow run nf-core/quantms -profile test,singularity --input project.sdrf.tsv --database protein.fasta --outdir ../outdir
N E X T F L O W  ~  version 22.10.4
Project `nf-core/quantms` is currently stickied on revision: 1.0 -- you need to explicitly specify a revision with the option `-r` in order to use it
```

Passing the `-r` makes it fail like the previous one.

Perhaps going forward the config should assign one of the `test_*` as `test`, which is what [other workflows with multiple tests](https://github.com/nf-core/eager/blob/master/nextflow.config) do.

**Comment by jpfeuffer** [comment]
Thanks. Fixed in `-r dev` long ago.
