### ISSUE TITLE
Post-release 1.1.1

### ISSUE THREAD

**Issue by fabianegli** [nf-core/quantms#98]
### Description of feature

There are a bunch of remaining tasks for post-release of 1.1.1:

## 1st Step
- [x] Update release date in CHANGELOG.md https://github.com/nf-core/quantms/pull/99 and https://github.com/nf-core/quantms/pull/100

## 2nd Step
- [x] Prepare CHANGELOG.md on the dev branch for future development https://github.com/nf-core/quantms/pull/100
- [x] Bump dev to new dev version (`nf-core bump-version 1.2.0dev`?) https://github.com/nf-core/quantms/pull/100

This PR is inspired by: https://nf-co.re/docs/contributing/release_checklist#steps-to-release

**Comment by ypriverol** [comment]
This has been done
